build:
  maxIssues: 0

naming:
  FunctionNaming:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: true
